debug: false
server:
  port: 8080
  servlet:
    context-path: /nacos
spring:
  application:
    name: nacos-spring-boot-example
nacos:
  config:
    server-addr: 192.168.56.101:8848
    namespace: 595669e1-765c-4005-9224-8e277f970da3