server:
  port: 8080
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.56.101:8847
        port: 8718
      filter:
        url-patterns:
          - '/*'
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.56.101:8848
            dataId: sentinel
            groupId: SENTINET-GROUP