debug: false
server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-example
  cloud:
    gateway:
      routes:
        - id: demo
          uri: https://www.baidu.com
          predicates:
            - Path=/s
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'