debug: false
server:
  port: 8080
  servlet:
    context-path: /nacos
#spring:
#  application:
#    name: nacos-spring-cloud-example
#  cloud:
#    nacos:
#      config:
#        server-addr: 192.168.56.101:8848